spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/layui?userSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
mybatis:
  type-aliases-package: api.entity
  mapper-locations: classpath:/danran/rpc/provider/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl